version: '3'

services:
###> symfony/mailer ###
  mailer:
    image: axllent/mailpit
    ports:
      - "1025"
      - "8025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
###< symfony/mailer ###
  mailhog:
    container_name: mailhog
    restart: always
    image: mailhog/mailhog:latest

    ports:
      - "8025:8025"
      - '1025:1025'
